language: haxe
haxe:
  - "3.2.0"
neko: "2.0.0"
install:
  - sh -c "if [ '$TARGET' = 'cpp' ]; then ./travis/cpp-setup.sh; fi"
  - sh -c "if [ '$TARGET' = 'node' ]; then ./travis/node-setup.sh; fi"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.4
env:
  - HXDECORATE_PLATFORM=cpp-linux
  - HXDECORATE_PLATFORM=js
  - HXDECORATE_PLATFORM=python-linux
script: haxe $HXDECORATE_PLATFORM.hxml
