language: haxe
haxe:
  - "3.2.0"
  - "3.2.1"
neko: "2.0.0"
install:
  - export SETUP_SCRIPT=${TRAVIS_BUILD_DIR}/travis/setup/${HXDECORATE_PLATFORM}-setup.sh
  - /bin/bash -c "if [ -e ${SETUP_SCRIPT} ]; then chmod +x ${SETUP_SCRIPT} && source ${SETUP_SCRIPT}; fi"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.4
env:
  - HXDECORATE_PLATFORM=cpp BUILD_TYPE=base
  - HXDECORATE_PLATFORM=node BUILD_TYPE=base
  - HXDECORATE_PLATFORM=python BUILD_TYPE=base
  - HXDECORATE_PLATFORM=java BUILD_TYPE=base
  - HXDECORATE_PLATFORM=cpp BUILD_TYPE=proxy
  - HXDECORATE_PLATFORM=node BUILD_TYPE=proxy
  - HXDECORATE_PLATFORM=python BUILD_TYPE=proxy
  - HXDECORATE_PLATFORM=java BUILD_TYPE=proxy
script: cd ${TRAVIS_BUILD_DIR}/travis/${BUILD_TYPE} && haxe ${HXDECORATE_PLATFORM}.hxml
