language: haxe
haxe:
  - "3.2.0"
  - "3.2.1"
neko: "2.0.0"
install:
  - sh -c "if [ '$HXDECORATE_PLATFORM' = 'cpp' ]; then chmod +x ${TRAVIS_BUILD_DIR}/travis/setup/cpp-setup.sh && ${TRAVIS_BUILD_DIR}/travis/setup/cpp-setup.sh; fi"
  - sh -c "if [ '$HXDECORATE_PLATFORM' = 'node' ] || [ '$HXDECORATE_PLATFORM' = 'iojs' ]; then chmod +x ${TRAVIS_BUILD_DIR}/travis/setup/node-setup.sh && ${TRAVIS_BUILD_DIR}/travis/setup/node-setup.sh; fi"
  - sh -c "if [ '$HXDECORATE_PLATFORM' = 'java' ]; then chmod +x ${TRAVIS_BUILD_DIR}/travis/setup/java-setup.sh && ${TRAVIS_BUILD_DIR}/travis/setup/java-setup.sh; fi"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.4
env:
  - HXDECORATE_PLATFORM=cpp
  - HXDECORATE_PLATFORM=node
  - HXDECORATE_PLATFORM=iojs
  - HXDECORATE_PLATFORM=python
  - HXDECORATE_PLATFORM=java
script: cd ${TRAVIS_BUILD_DIR}/travis && haxe $HXDECORATE_PLATFORM.hxml
