language: haxe
haxe:
  - "3.2.0"
neko: "2.0.0"
install:
  - haxelib install hxcpp
  - curl https://iojs.org/dist/latest/iojs-v3.3.0-linux-x64.tar.gz > iojs.tar.gz
  - tar -zxvf iojs.tar.gz -C ~
  - export PATH=$PATH:~/iojs-v3.3.0-linux-x64/bin
  - chmod +x ~/iojs-v3.3.0-linux-x64/bin/iojs
  - chmod +x ~/iojs-v3.3.0-linux-x64/bin/node
  - iojs -v
  - node -v
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.4
env:
  - HXDECORATE_PLATFORM=cpp
  - HXDECORATE_PLATFORM=js
  - HXDECORATE_PLATFORM=python
script: haxe $HXDECORATE_PLATFORM.hxml